name = "artie-hannah-sanders"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
VIEWER_PASSWORD = "1123"
ARTIST_NAME = "Hannah Sanders"

[[d1_databases]]
binding = "DB"
database_name = "artie-hannah-sanders-db"
database_id = "29a538c3-feff-4b09-9ed2-00d59495ff68"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "artie-site-images"
