name = "artie-don"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
ARTIST_NAME = "Don Golden"

[[d1_databases]]
binding = "DB"
database_name = "artie-don-db"
database_id = "d4d25e9c-6f93-4d02-a73e-93f07ee49348"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "artie-don-images"
