name = "kathy-artie"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
ARTIST_NAME = "Kathy Golden"

[[d1_databases]]
binding = "DB"
database_name = "kathy-catalog-db"
database_id = "ad908b94-bdc3-46cb-a648-c1124f2e9429"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "kathy-catalog-images"
