-- Update image_keys for all artworks from docx import
UPDATE artworks SET image_key='Winslow_Sunrise.jpg' WHERE title='Winslow Sunrise' AND image_key IS NULL;
UPDATE artworks SET image_key='Route_66.jpg' WHERE title='Route 66' AND image_key IS NULL;
UPDATE artworks SET image_key='Glider_Trip.jpg' WHERE title='Glider Trip' AND image_key IS NULL;
UPDATE artworks SET image_key='EastBound.jpg' WHERE title='EastBound' AND image_key IS NULL;
UPDATE artworks SET image_key='Sunset_Beauty.jpg' WHERE title='Sunset Beauty' AND image_key IS NULL;
UPDATE artworks SET image_key='Janela_de_Pedra.jpg' WHERE title='Janela de Pedra' AND image_key IS NULL;
UPDATE artworks SET image_key='OculusRevised_23_Dec17.jpg' WHERE title='OculusRevised 23 Dec17' AND image_key IS NULL;
UPDATE artworks SET image_key='Four_Five_Victor.jpg' WHERE title='Four Five Victor' AND image_key IS NULL;
UPDATE artworks SET image_key='Silver_Axe.jpg' WHERE title='Silver Axe' AND image_key IS NULL;
UPDATE artworks SET image_key='Steel_Beak.jpg' WHERE title='Steel Beak' AND image_key IS NULL;
UPDATE artworks SET image_key='Remember.jpg' WHERE title='Remember' AND image_key IS NULL;
UPDATE artworks SET image_key='SAC.jpg' WHERE title='SAC' AND image_key IS NULL;
UPDATE artworks SET image_key='Blue_Heron.jpg' WHERE title='Blue Heron' AND image_key IS NULL;
UPDATE artworks SET image_key='Into_The_Breach.jpg' WHERE title='Into The Breach' AND image_key IS NULL;
UPDATE artworks SET image_key='Cruise_Rise.jpg' WHERE title='Cruise Rise' AND image_key IS NULL;
UPDATE artworks SET image_key='Cup_Racer.jpg' WHERE title='Cup Racer' AND image_key IS NULL;
UPDATE artworks SET image_key='Texas_Gold.jpg' WHERE title='Texas Gold' AND image_key IS NULL;
UPDATE artworks SET image_key='Bolivar_LightHouse.jpg' WHERE title='Bolivar LightHouse' AND image_key IS NULL;
UPDATE artworks SET image_key='Pepper_and_Salt.jpg' WHERE title='Pepper and Salt' AND image_key IS NULL;
UPDATE artworks SET image_key='Aquaduct.jpg' WHERE title='Aquaduct' AND image_key IS NULL;
UPDATE artworks SET image_key='Peeking_Duck.jpg' WHERE title='Peeking Duck' AND image_key IS NULL;
UPDATE artworks SET image_key='Boliver_Inlet.jpg' WHERE title='Boliver Inlet' AND image_key IS NULL;
UPDATE artworks SET image_key='Touch.jpg' WHERE title='Touch' AND image_key IS NULL;
UPDATE artworks SET image_key='Derniere_Rose_de_Automne.jpg' WHERE title='Derniere Rose de Automne' AND image_key IS NULL;
UPDATE artworks SET image_key='Bryce_Amphitheater.jpg' WHERE title='Bryce Amphitheater' AND image_key IS NULL;
UPDATE artworks SET image_key='End_of_Autumn.jpg' WHERE title='End of Autumn' AND image_key IS NULL;
UPDATE artworks SET image_key='Panhandle_Dawn.jpg' WHERE title='Panhandle Dawn' AND image_key IS NULL;
UPDATE artworks SET image_key='Prairie_Dawn.jpg' WHERE title='Prairie Dawn' AND image_key IS NULL;
UPDATE artworks SET image_key='Cygne_Noir.jpg' WHERE title='Cygne Noir' AND image_key IS NULL;
UPDATE artworks SET image_key='Angel_Trumpet.jpg' WHERE title='Angel Trumpet' AND image_key IS NULL;
UPDATE artworks SET image_key='Arches_of_Notre_Dame.jpg' WHERE title='Arches of Notre Dame' AND image_key IS NULL;
UPDATE artworks SET image_key='Fortress_Portal.jpg' WHERE title='Fortress Portal' AND image_key IS NULL;
UPDATE artworks SET image_key='High_Plains.jpg' WHERE title='High Plains' AND image_key IS NULL;
UPDATE artworks SET image_key='Chief.jpg' WHERE title='Chief' AND image_key IS NULL;
UPDATE artworks SET image_key='Behind_the_Veil.jpg' WHERE title='Behind the Veil' AND image_key IS NULL;
UPDATE artworks SET image_key='Blowin_in_the_Wind.jpg' WHERE title='Blowin in the Wind' AND image_key IS NULL;
UPDATE artworks SET image_key='Eifel_Sunset.jpg' WHERE title='Eifel Sunset' AND image_key IS NULL;
UPDATE artworks SET image_key='Bedouin_in_Pink.jpg' WHERE title='Bedouin in Pink' AND image_key IS NULL;
UPDATE artworks SET image_key='Clean_Machine.jpg' WHERE title='Clean Machine' AND image_key IS NULL;
UPDATE artworks SET image_key='DR_Boy.jpg' WHERE title='DR Boy' AND image_key IS NULL;
UPDATE artworks SET image_key='DR_Girl.jpg' WHERE title='DR Girl' AND image_key IS NULL;
UPDATE artworks SET image_key='Eiffel_Sunset.jpg' WHERE title='Eiffel Sunset' AND image_key IS NULL;
UPDATE artworks SET image_key='Kathys_Orchid.jpg' WHERE title='Kathys Orchid' AND image_key IS NULL;
UPDATE artworks SET image_key='My_Wings.jpg' WHERE title='My Wings' AND image_key IS NULL;
UPDATE artworks SET image_key='Hangin_On.jpg' WHERE title='Hangin On' AND image_key IS NULL;
UPDATE artworks SET image_key='Monument.jpg' WHERE title='Monument' AND image_key IS NULL;
UPDATE artworks SET image_key='Sunset_at_Home.jpg' WHERE title='Sunset at Home' AND image_key IS NULL;
UPDATE artworks SET image_key='Declaration.jpg' WHERE title='Declaration' AND image_key IS NULL;
UPDATE artworks SET image_key='Joy.jpg' WHERE title='Joy' AND image_key IS NULL;
UPDATE artworks SET image_key='Night_Bridge.jpg' WHERE title='Night Bridge' AND image_key IS NULL;
UPDATE artworks SET image_key='ICU.jpg' WHERE title='ICU' AND image_key IS NULL;
UPDATE artworks SET image_key='Trolling.jpg' WHERE title='Trolling' AND image_key IS NULL;
UPDATE artworks SET image_key='Tiptoes.jpg' WHERE title='Tiptoes' AND image_key IS NULL;
UPDATE artworks SET image_key='Half_and_A_Little.jpg' WHERE title='Half and A Little' AND image_key IS NULL;
UPDATE artworks SET image_key='Ranch_Wind_Power.jpg' WHERE title='Ranch Wind Power' AND image_key IS NULL;
UPDATE artworks SET image_key='Ranch_Couple.jpg' WHERE title='Ranch Couple' AND image_key IS NULL;
UPDATE artworks SET image_key='Ranch_Butt.jpg' WHERE title='Ranch Butt' AND image_key IS NULL;
UPDATE artworks SET image_key='George_Ranch_House.jpg' WHERE title='George Ranch House' AND image_key IS NULL;
UPDATE artworks SET image_key='The_Door.jpg' WHERE title='The Door' AND image_key IS NULL;
UPDATE artworks SET image_key='Reclaiming.jpg' WHERE title='Reclaiming' AND image_key IS NULL;
UPDATE artworks SET image_key='Zoo_Zoom.jpg' WHERE title='Zoo Zoom' AND image_key IS NULL;
UPDATE artworks SET image_key='Celebration.jpg' WHERE title='Celebration' AND image_key IS NULL;
UPDATE artworks SET image_key='Orion.jpg' WHERE title='Orion' AND image_key IS NULL;
UPDATE artworks SET image_key='Nelsons_Trumpet.jpg' WHERE title='Nelsons Trumpet' AND image_key IS NULL;
UPDATE artworks SET image_key='Junior.jpg' WHERE title='Junior' AND image_key IS NULL;
UPDATE artworks SET image_key='Visitor.jpg' WHERE title='Visitor' AND image_key IS NULL;
UPDATE artworks SET image_key='Dancer.jpg' WHERE title='Dancer' AND image_key IS NULL;
UPDATE artworks SET image_key='Fishin.jpg' WHERE title='Fishin' AND image_key IS NULL;
UPDATE artworks SET image_key='Splash.jpg' WHERE title='Splash' AND image_key IS NULL;
UPDATE artworks SET image_key='Splish.jpg' WHERE title='Splish' AND image_key IS NULL;
UPDATE artworks SET image_key='Into_My_Parlor.jpg' WHERE title='Into My Parlor' AND image_key IS NULL;
UPDATE artworks SET image_key='Launch.jpg' WHERE title='Launch' AND image_key IS NULL;
UPDATE artworks SET image_key='Pink_Lady.jpg' WHERE title='Pink Lady' AND image_key IS NULL;
UPDATE artworks SET image_key='Heres_Lookin_At_You.jpg' WHERE title='Heres Lookin At You' AND image_key IS NULL;
UPDATE artworks SET image_key='Hunters_Moon.jpg' WHERE title='Hunters Moon' AND image_key IS NULL;
UPDATE artworks SET image_key='PGCC.jpg' WHERE title='PGCC' AND image_key IS NULL;
UPDATE artworks SET image_key='Big_Boy_on_the_Bridge.jpg' WHERE title='Big Boy on the Bridge' AND image_key IS NULL;
UPDATE artworks SET image_key='4014.jpg' WHERE title='4014' AND image_key IS NULL;
UPDATE artworks SET image_key='Cypress_Convergence.jpg' WHERE title='Cypress Convergence' AND image_key IS NULL;
UPDATE artworks SET image_key='Short_Walk.jpg' WHERE title='Short Walk' AND image_key IS NULL;
UPDATE artworks SET image_key='Galleria.jpg' WHERE title='Galleria' AND image_key IS NULL;
UPDATE artworks SET image_key='Turrell_Tunnel.jpg' WHERE title='Turrell Tunnel' AND image_key IS NULL;
UPDATE artworks SET image_key='Starter_Set.jpg' WHERE title='Starter Set' AND image_key IS NULL;
UPDATE artworks SET image_key='Santa_Elena_Canyon.jpg' WHERE title='Santa Elena Canyon' AND image_key IS NULL;
UPDATE artworks SET image_key='West_of_the_Pecos.jpg' WHERE title='West of the Pecos' AND image_key IS NULL;
UPDATE artworks SET image_key='Lookin_Back.jpg' WHERE title='Lookin Back' AND image_key IS NULL;
UPDATE artworks SET image_key='Big_Boy_Bridge.jpg' WHERE title='Big Boy Bridge' AND image_key IS NULL;
UPDATE artworks SET image_key='Gentle_Peace.jpg' WHERE title='Gentle Peace' AND image_key IS NULL;
UPDATE artworks SET image_key='Lonely_Bridge.jpg' WHERE title='Lonely Bridge' AND image_key IS NULL;
UPDATE artworks SET image_key='Loretto_Staircase.jpg' WHERE title='Loretto Staircase' AND image_key IS NULL;
UPDATE artworks SET image_key='Whoa.jpg' WHERE title='Whoa' AND image_key IS NULL;
UPDATE artworks SET image_key='Anderson_Hotel.jpg' WHERE title='Anderson Hotel' AND image_key IS NULL;
UPDATE artworks SET image_key='Splash_of_Color.jpg' WHERE title='Splash of Color' AND image_key IS NULL;
UPDATE artworks SET image_key='Calm_Above.jpg' WHERE title='Calm Above' AND image_key IS NULL;
UPDATE artworks SET image_key='Breakfast.jpg' WHERE title='Breakfast' AND image_key IS NULL;
UPDATE artworks SET image_key='Caribbean_Encounter.jpg' WHERE title='Caribbean Encounter' AND image_key IS NULL;
UPDATE artworks SET image_key='Ghost_Ship.jpg' WHERE title='Ghost Ship' AND image_key IS NULL;
UPDATE artworks SET image_key='Sunsight_Dawn.jpg' WHERE title='Sunsight Dawn' AND image_key IS NULL;
UPDATE artworks SET image_key='Rigging_at_Dawn.jpg' WHERE title='Rigging at Dawn' AND image_key IS NULL;
UPDATE artworks SET image_key='Dawn_at_Sea.jpg' WHERE title='Dawn at Sea' AND image_key IS NULL;
UPDATE artworks SET image_key='Misty_View.jpg' WHERE title='Misty View' AND image_key IS NULL;
UPDATE artworks SET image_key='Rudder_and_Prop.jpg' WHERE title='Rudder and Prop' AND image_key IS NULL;
UPDATE artworks SET image_key='Drydock.jpg' WHERE title='Drydock' AND image_key IS NULL;
UPDATE artworks SET image_key='Reflection.jpg' WHERE title='Reflection' AND image_key IS NULL;
UPDATE artworks SET image_key='EiffelFantasy.jpg' WHERE title='EiffelFantasy' AND image_key IS NULL;
UPDATE artworks SET image_key='Boot_Hill.jpg' WHERE title='Boot Hill' AND image_key IS NULL;
UPDATE artworks SET image_key='Small_Splash.jpg' WHERE title='Small Splash' AND image_key IS NULL;
UPDATE artworks SET image_key='Boobies_in_Formation.jpg' WHERE title='Boobies in Formation' AND image_key IS NULL;
UPDATE artworks SET image_key='LeglieseAuversSurOise.jpg' WHERE title='LeglieseAuversSurOise' AND image_key IS NULL;
UPDATE artworks SET image_key='Paris_Street.jpg' WHERE title='Paris Street' AND image_key IS NULL;
UPDATE artworks SET image_key='Reflections.jpg' WHERE title='Reflections' AND image_key IS NULL;
UPDATE artworks SET image_key='Creative_Hands.jpg' WHERE title='Creative Hands' AND image_key IS NULL;
UPDATE artworks SET image_key='Intelligent_Design.jpg' WHERE title='Intelligent Design' AND image_key IS NULL;
UPDATE artworks SET image_key='Morning_Training.jpg' WHERE title='Morning Training' AND image_key IS NULL;
UPDATE artworks SET image_key='Mothers_Love.jpg' WHERE title='Mothers Love' AND image_key IS NULL;
UPDATE artworks SET image_key='Rose_at_Dawn.jpg' WHERE title='Rose at Dawn' AND image_key IS NULL;
UPDATE artworks SET image_key='Self_Portrait.jpg' WHERE title='Self Portrait' AND image_key IS NULL;
UPDATE artworks SET image_key='Pleiades.jpg' WHERE title='Pleiades' AND image_key IS NULL;
UPDATE artworks SET image_key='Sovereign_SGR.jpg' WHERE title='Sovereign SGR' AND image_key IS NULL;
UPDATE artworks SET image_key='Two_Blues_and_a_Hawk.jpg' WHERE title='Two Blues and a Hawk' AND image_key IS NULL;
UPDATE artworks SET image_key='Ocean_Going_Tug.jpg' WHERE title='Ocean Going Tug' AND image_key IS NULL;
UPDATE artworks SET image_key='Skeeter_Hawk.jpg' WHERE title='Skeeter Hawk' AND image_key IS NULL;
UPDATE artworks SET image_key='Making_the_Turn.jpg' WHERE title='Making the Turn' AND image_key IS NULL;
UPDATE artworks SET image_key='Headin_South.jpg' WHERE title='Headin South' AND image_key IS NULL;
UPDATE artworks SET image_key='Through_a_Glass_Darkly.jpg' WHERE title='Through a Glass Darkly' AND image_key IS NULL;
UPDATE artworks SET image_key='Crystal_Break.jpg' WHERE title='Crystal Break' AND image_key IS NULL;
UPDATE artworks SET image_key='Fog_Rolling_In.jpg' WHERE title='Fog Rolling In' AND image_key IS NULL;
UPDATE artworks SET image_key='Sunrise.jpg' WHERE title='Sunrise' AND image_key IS NULL;